In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_pacf

df = pd.read_excel('temperature_inples.xlsx')

pacf graph to see lag term

In [2]:
data = df["Average Temperature_x"].to_numpy()



虛擬變數資料處理

In [3]:
tran=pd.concat([df['Average Temperature_x'],df['encode_state']],axis=1)

In [4]:
# 假设你有一个名为 df 的 DataFrame 对象，其中包含你的时间序列数据和虚拟变量
# 时间序列数据存储在列 'TS1' 和 'TS2' 中，虚拟变量存储在列 'Season' 中

# 将 'Season' 列转换为虚拟变量
##df_with_dummies = pd.get_dummies(df, columns=['encode_state']), drop_first=True)
df_with_dummies = pd.get_dummies(tran, columns=['encode_state'])

In [5]:
ts_data = df_with_dummies[['Average Temperature_x']] ## 時間序列
exog_data = df_with_dummies.drop(['Average Temperature_x'], axis=1) ## 外生變數

In [6]:
import numpy as np
## 轉為數列
ts_data_array = np.asarray(ts_data) 
exog_data_array = np.asarray(exog_data)

ARIMA MODEL WITH DUMMY VARIABLES

In [7]:
from statsmodels.tsa.arima.model import ARIMA

In [9]:

import statsmodels.api as sm

In [10]:
# 擬合 ARIMAX 模型
model = sm.tsa.ARIMA(endog=ts_data_array, exog=exog_data_array, order=(11, 0, 10))
model_fit = model.fit()

c:\Users\nancy\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


In [11]:
len(ts_data_array)

13716

In [ ]:
exog_forecast=ts_data[12:].to_numpy(dtype=float)

In [ ]:
# 預測未來值
#exog_forecast = train_data_with_dummy 
forecast = model_fit.predict(start=13, end=len(ts_data), exog=exog_forecast)



In [187]:
model_arima_fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results                                
==============================================================================
Dep. Variable:                      y   No. Observations:                13860
Model:               ARIMA(11, 0, 11)   Log Likelihood               32795.335
Date:                Sun, 04 Jun 2023   AIC                         -65512.671
Time:                        23:33:35   BIC                         -65218.737
Sample:                             0   HQIC                        -65414.769
                              - 13860                                         
Covariance Type:                  opg                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0400      0.009     -4.404      0.000      -0.058      -0.022
x1         -7.311e-09   4.45e-08     -0.164      0.869   -9.44e-08    7.98e-08
x2             0.4720      0.005     89.678      0.000       0.462       0.482
x3             0.5017      0.000   2073.221      0.000       0.501       0.502
x4            -0.2378      0.003    -89.987      0.000      -0.243      -0.233
x5             0.4984      0.000   1873.909      0.000       0.498       0.499
x6            -0.2343      0.003    -88.328      0.000      -0.239      -0.229
x7            -0.0090      0.002     -5.339      0.000      -0.012      -0.006
x8            -0.0059      0.001     -5.174      0.000      -0.008      -0.004
x9             0.0005      0.001      0.472      0.637      -0.001       0.002
x10           -0.0083      0.001     -7.573      0.000      -0.010      -0.006
x11           -0.0055      0.001     -4.347      0.000      -0.008      -0.003
x12           -0.0092      0.001     -8.709      0.000      -0.011      -0.007
x13            0.0026      0.001      2.477      0.013       0.001       0.005
x14           -0.0081      0.001     -6.805      0.000      -0.010      -0.006
x15            0.0029      0.001      2.605      0.009       0.001       0.005
ar.L1         -0.3685      0.007    -53.882      0.000      -0.382      -0.355
ar.L2         -0.7400      0.008    -97.573      0.000      -0.755      -0.725
ar.L3         -0.5130      0.007    -74.960      0.000      -0.526      -0.500
ar.L4         -0.4195      0.008    -49.703      0.000      -0.436      -0.403
ar.L5         -0.6882      0.008    -81.269      0.000      -0.705      -0.672
ar.L6         -0.3092      0.006    -49.406      0.000      -0.322      -0.297
ar.L7         -0.6644      0.008    -82.604      0.000      -0.680      -0.649
ar.L8         -0.3841      0.008    -45.949      0.000      -0.400      -0.368
ar.L9         -0.4262      0.007    -61.216      0.000      -0.440      -0.413
ar.L10        -0.6509      0.008    -84.595      0.000      -0.666      -0.636
ar.L11        -0.2747      0.008    -34.584      0.000      -0.290      -0.259
ma.L1          0.3427      0.010     33.074      0.000       0.322       0.363
ma.L2          0.6552      0.012     55.540      0.000       0.632       0.678
ma.L3          0.4428      0.008     52.479      0.000       0.426       0.459
ma.L4          0.3032      0.010     30.208      0.000       0.284       0.323
ma.L5          0.5413      0.011     51.312      0.000       0.521       0.562
ma.L6          0.1822      0.008     22.310      0.000       0.166       0.198
ma.L7          0.4674      0.011     44.361      0.000       0.447       0.488
ma.L8          0.2328      0.011     21.683      0.000       0.212       0.254
ma.L9          0.2382      0.009     26.575      0.000       0.221       0.256
ma.L10         0.4543      0.010     44.180      0.000       0.434       0.474
ma.L11         0.1034      0.013      8.019      0.000       0.078       0.129
si

看預測結果

In [191]:
outs = pd.DataFrame({'temperatures':predicted_values})
outs.to_excel('outs.xlsx', sheet_name='temperatures', index=False)

In [192]:
len(predicted_values)

13860

In [135]:
observed_values

array([[21.6],
       [19.2],
       [31.7],
       ...,
       [52.1],
       [60.4],
       [64.6]])

In [137]:
ALL_AREA = pd.read_excel("ALL AREA.xlsx")

In [138]:
ALL_AREA

Unnamed: 0    Date  Average Temperature  Anomaly  Maximun Temperature  \
0          1524  202201                 26.6      2.9                 40.4   
1          1525  202202                 25.0     -2.2                 39.1   
2          1526  202203                 35.0      1.4                 49.0   
3          1527  202204                 43.7      1.2                 58.9   
4          1528  202205                 53.3      1.4                 68.0   
..          ...     ...                  ...      ...                  ...   
103        1531  202208                 83.3      1.4                 94.4   
104        1532  202209                 77.8      1.9                 90.2   
105        1533  202210                 66.4      0.4                 79.6   
106        1534  202211                 54.0     -0.6                 64.8   
107        1535  202212                 50.0      3.2                 61.1   

     Anomaly.1   Minimum Temperature  Anomaly.2  encode_state  
0          4.0                  12.8        1.8             0  
1         -1.3                  10.9       -3.2             0  
2          2.2                  20.9        0.5             0  
3          2.7                  28.5       -0.4             0  
4          2.2                  38.5        0.6             0  
..         ...                   ...        ...           ...  
103        0.2                  72.2        2.7             8  
104        2.2                  65.3        1.6             8  
105        0.8                  53.2        0.0             8  
106       -2.3                  43.2        1.2             8  
107        2.2                  38.9        4.2             8  

[108 rows x 9 columns]

In [139]:
ALL_AREA = pd.get_dummies(ALL_AREA, columns=['encode_state'])

In [140]:
ALL_AREA

Unnamed: 0    Date  Average Temperature  Anomaly  Maximun Temperature  \
0          1524  202201                 26.6      2.9                 40.4   
1          1525  202202                 25.0     -2.2                 39.1   
2          1526  202203                 35.0      1.4                 49.0   
3          1527  202204                 43.7      1.2                 58.9   
4          1528  202205                 53.3      1.4                 68.0   
..          ...     ...                  ...      ...                  ...   
103        1531  202208                 83.3      1.4                 94.4   
104        1532  202209                 77.8      1.9                 90.2   
105        1533  202210                 66.4      0.4                 79.6   
106        1534  202211                 54.0     -0.6                 64.8   
107        1535  202212                 50.0      3.2                 61.1   

     Anomaly.1   Minimum Temperature  Anomaly.2  encode_state_0  \
0          4.0                  12.8        1.8               1   
1         -1.3                  10.9       -3.2               1   
2          2.2                  20.9        0.5               1   
3          2.7                  28.5       -0.4               1   
4          2.2                  38.5        0.6               1   
..         ...                   ...        ...             ...   
103        0.2                  72.2        2.7               0   
104        2.2                  65.3        1.6               0   
105        0.8                  53.2        0.0               0   
106       -2.3                  43.2        1.2               0   
107        2.2                  38.9        4.2               0   

     encode_state_1  encode_state_2  encode_state_3  encode_state_4  \
0                 0               0               0               0   
1                 0               0               0               0   
2                 0               0               0               0   
3                 0               0               0               0   
4                 0               0               0               0   
..              ...             ...             ...             ...   
103               0               0               0               0   
104               0               0               0               0   
105               0               0               0               0   
106               0               0               0               0   
107               0               0               0               0   

     encode_state_5  encode_state_6  encode_state_7  encode_state_8  
0                 0               0               0               0  
1                 0               0               0               0  
2                 0               0               0               0  
3                 0               0               0               0  
4                 0               0               0               0  
..              ...             ...             ...             ...  
103               0               0               0               1  
104               0               0               0               1  
105               0               0               0               1  
106               0               0               0               1  
107               0               0               0               1  

[108 rows x 17 columns]

In [141]:
ALL_AREA = ALL_AREA.drop(['Average Temperature', "Unnamed: 0"], axis=1)

In [142]:
ALL_AREA

Date  Anomaly  Maximun Temperature  Anomaly.1   Minimum Temperature  \
0    202201      2.9                 40.4        4.0                  12.8   
1    202202     -2.2                 39.1       -1.3                  10.9   
2    202203      1.4                 49.0        2.2                  20.9   
3    202204      1.2                 58.9        2.7                  28.5   
4    202205      1.4                 68.0        2.2                  38.5   
..      ...      ...                  ...        ...                   ...   
103  202208      1.4                 94.4        0.2                  72.2   
104  202209      1.9                 90.2        2.2                  65.3   
105  202210      0.4                 79.6        0.8                  53.2   
106  202211     -0.6                 64.8       -2.3                  43.2   
107  202212      3.2                 61.1        2.2                  38.9   

     Anomaly.2  encode_state_0  encode_state_1  encode_state_2  \
0          1.8               1               0               0   
1         -3.2               1               0               0   
2          0.5               1               0               0   
3         -0.4               1               0               0   
4          0.6               1               0               0   
..         ...             ...             ...             ...   
103        2.7               0               0               0   
104        1.6               0               0               0   
105        0.0               0               0               0   
106        1.2               0               0               0   
107        4.2               0               0               0   

     encode_state_3  encode_state_4  encode_state_5  encode_state_6  \
0                 0               0               0               0   
1                 0               0               0               0   
2                 0               0               0               0   
3                 0               0               0               0   
4                 0               0               0               0   
..              ...             ...             ...             ...   
103               0               0               0               0   
104               0               0               0               0   
105               0               0               0               0   
106               0               0               0               0   
107               0               0               0               0   

     encode_state_7  encode_state_8  
0                 0               0  
1                 0               0  
2                 0               0  
3                 0               0  
4                 0               0  
..              ...             ...  
103               0               1  
104               0               1  
105               0               1  
106               0               1  
107               0               1  

[108 rows x 15 columns]

In [143]:
ALL_AREA = np.asarray(ALL_AREA)

In [144]:
ALL_AREA

array([[ 2.02201e+05,  2.90000e+00,  4.04000e+01, ...,  0.00000e+00,
         0.00000e+00,  0.00000e+00],
       [ 2.02202e+05, -2.20000e+00,  3.91000e+01, ...,  0.00000e+00,
         0.00000e+00,  0.00000e+00],
       [ 2.02203e+05,  1.40000e+00,  4.90000e+01, ...,  0.00000e+00,
         0.00000e+00,  0.00000e+00],
       ...,
       [ 2.02210e+05,  4.00000e-01,  7.96000e+01, ...,  0.00000e+00,
         0.00000e+00,  1.00000e+00],
       [ 2.02211e+05, -6.00000e-01,  6.48000e+01, ...,  0.00000e+00,
         0.00000e+00,  1.00000e+00],
       [ 2.02212e+05,  3.20000e+00,  6.11000e+01, ...,  0.00000e+00,
         0.00000e+00,  1.00000e+00]])

In [205]:
Areas = []
for i in range(9):
    nums = []
    for j in range(12):
        num = i * 12 + j
        nums.append(ALL_AREA[num])
    Areas.append(nums)

In [206]:
Areas

[[array([2.02201e+05, 2.90000e+00, 4.04000e+01, 4.00000e+00, 1.28000e+01,
         1.80000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
         0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00]),
  array([ 2.02202e+05, -2.20000e+00,  3.91000e+01, -1.30000e+00,
          1.09000e+01, -3.20000e+00,  1.00000e+00,  0.00000e+00,
          0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
          0.00000e+00,  0.00000e+00,  0.00000e+00]),
  array([2.02203e+05, 1.40000e+00, 4.90000e+01, 2.20000e+00, 2.09000e+01,
         5.00000e-01, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
         0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00]),
  array([ 2.02204e+05,  1.20000e+00,  5.89000e+01,  2.70000e+00,
          2.85000e+01, -4.00000e-01,  1.00000e+00,  0.00000e+00,
          0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
          0.00000e+00,  0.00000e+00,  0.00000e+00]),
  array([2.02205e+05, 1.40000e+00, 6.80000e+01, 2.20000e

In [229]:
for i in range(9):
    print(model_arima_fit.forecast(12, exog = Areas[i]))

[26.59884548 25.02209533 34.96859017 43.725786   53.26025069 64.28513872
 70.31111737 67.8013514  62.48763463 47.61491481 31.27344417 25.55926455]
[29.84823865 31.82642042 44.12160423 54.10525321 64.68434355 75.80841935
 81.05955199 79.18011061 72.01069822 57.74280402 41.09956056 30.61130839]
[ 3.54566887  6.54492344 26.16498983 35.53000516 55.34185507 66.18142431
 69.68735807 67.2816526  60.20943339 46.93873325 30.13813847 12.58103991]
[22.88638377 22.41339438 33.46101252 35.19403556 48.60318742 58.47773687
 69.11144252 69.73316339 60.65781877 47.18222085 22.56208206 14.62413675]
[25.57456097 26.77139988 37.99589096 46.50473777 58.7620022  71.40650957
 76.41141949 74.87886331 67.38955235 52.19188682 34.37167    22.68426739]
[ 8.6862838   9.41179996 26.90705216 33.56924854 52.93118905 64.59657501
 70.63230822 69.49962372 60.90635966 45.95800469 23.05984785  6.74315848]
[36.98392895 38.51217136 50.38300965 61.01279703 70.51760847 79.33805007
 86.54266733 82.41458305 75.89386187 62.00046

In [243]:
forecast = model_arima_fit.predict(start = 1, end = int(round((len(ts_data_array)), 0)) + len(exog_data_array) - 1, exog = exog_data_array)

In [244]:
len(forecast)

27719