In [1]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np

from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()

X = cancer.data
y = cancer.target

print(X)
print(y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [2]:
# Decision Tree (Split data randomly from 90~10% + different depth + different min sample leaf)
from sklearn import tree
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()
X = cancer.data
y = cancer.target

ratio = 100
ratiovalues = [i for i in range(5, ratio, 5)]
relative_best_train_score = 0
relative_best_test_score = 0
relative_best_ratio = 0


for k in ratiovalues:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = k/100, random_state=71)
    clf = tree.DecisionTreeClassifier(random_state = 71)
    clf.fit(X_train, y_train)
    y_pred_train = clf.predict(X_train) #train
    train_acc = accuracy_score(y_pred_train, y_train)
    y_pred_test = clf.predict(X_test) #train
    test_acc = accuracy_score(y_pred_test, y_test)

    if ((train_acc > relative_best_train_score) and (test_acc > relative_best_test_score)):
        relative_best_train_score = train_acc
        relative_best_test_score = test_acc
        relative_best_ratio = k

print("best ratio of testing data:", relative_best_ratio, "Testing score:", relative_best_test_score)

best ratio of testing data: 5 Testing score: 0.9655172413793104


In [2]:
# RandomForest
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()
X = cancer.data
y = cancer.target

ratio = 100
ratiovalues = [i for i in range(5, ratio, 5)]
relative_best_train_score = 0
relative_best_test_score = 0
relative_best_ratio = 0


for k in ratiovalues:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = k/100, random_state=71)
    clf = RandomForestClassifier(random_state = 71)
    clf.fit(X_train, y_train)
    y_pred_train = clf.predict(X_train) #train
    train_acc = accuracy_score(y_pred_train, y_train)
    y_pred_test = clf.predict(X_test) #train
    test_acc = accuracy_score(y_pred_test, y_test)

    if ((train_acc > relative_best_train_score) and (test_acc > relative_best_test_score)):
        relative_best_train_score = train_acc
        relative_best_test_score = test_acc
        relative_best_ratio = k

print("best ratio of testing data:", relative_best_ratio, "Testing score:", relative_best_test_score)

NameError: name 'train_test_split' is not defined

In [3]:
# XGBoost
from xgboost.sklearn import XGBClassifier
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()
X = cancer.data
y = cancer.target

ratio = 100
ratiovalues = [i for i in range(5, ratio, 5)]
relative_best_train_score = 0
relative_best_test_score = 0
relative_best_ratio = 0


for k in ratiovalues:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = k/100, random_state=71)
    clf = XGBClassifier(random_state = 71)
    clf.fit(X_train, y_train)
    y_pred_train = clf.predict(X_train) #train
    train_acc = accuracy_score(y_pred_train, y_train)
    y_pred_test = clf.predict(X_test) #train
    test_acc = accuracy_score(y_pred_test, y_test)

    if ((train_acc > relative_best_train_score) and (test_acc > relative_best_test_score)):
        relative_best_train_score = train_acc
        relative_best_test_score = test_acc
        relative_best_ratio = k


print("best ratio of testing data:", relative_best_ratio, "Testing score:", relative_best_test_score)

ModuleNotFoundError: No module named 'xgboost'

In [ ]:
# SVC
from sklearn import svm
X = cancer.data
y = cancer.target

ratio = 100
ratiovalues = [i for i in range(5, ratio, 5)]
kernelvalues = ["rbf", "poly"]#, "sigmoid"]
gammavalues =["scale"]#, "auto"]
relative_best_train_score = 0
relative_best_test_score = 0
relative_best_ratio = 0


for k in ratiovalues:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = k/100, random_state=71)
    clf = svm.SVC(random_state = 71)
    clf.fit(X_train, y_train)
    y_pred_train = clf.predict(X_train) #train
    train_acc = accuracy_score(y_pred_train, y_train)
    y_pred_test = clf.predict(X_test) #train
    test_acc = accuracy_score(y_pred_test, y_test)

    if ((train_acc > relative_best_train_score) and (test_acc > relative_best_test_score)):
        relative_best_train_score = train_acc
        relative_best_test_score = test_acc
        relative_best_ratio = k

print("best ratio of testing data:", relative_best_ratio,  "Testing score:", relative_best_test_score)

In [ ]:
# KNN
from sklearn import neighbors
X = cancer.data
y = cancer.target

ratio = 100
ratiovalues = [i for i in range(5, ratio, 5)]
relative_best_train_score = 0
relative_best_test_score = 0
relative_best_ratio = 0


for k in ratiovalues:
    clf = neighbors.KNeighborsClassifier(n_neighbors = i, p = j)
    clf.fit(X_train, y_train)
    y_pred_train = clf.predict(X_train) #train
    train_acc = accuracy_score(y_pred_train, y_train)
    y_pred_test = clf.predict(X_test) #train
    test_acc = accuracy_score(y_pred_test, y_test)

    if ((train_acc > relative_best_train_score) and (test_acc > relative_best_test_score)):
        relative_best_train_score = train_acc
        relative_best_test_score = test_acc
        relative_best_ratio = k


print("best ratio of testing data:", relative_best_ratio, "Testing score:", relative_best_test_score)

In [ ]:
# Logistic regression
from sklearn.linear_model import LogisticRegression
X = cancer.data
y = cancer.target

ratio = 100
ratiovalues = [i for i in range(5, ratio, 5)]
relative_best_train_score = 0
relative_best_test_score = 0
relative_best_ratio = 0


for k in ratiovalues:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = k/100, random_state=71)
    clf = LogisticRegression(random_state = 71, penalty = i)
    clf.fit(X_train, y_train)
    y_pred_train = clf.predict(X_train) #train
    train_acc = accuracy_score(y_pred_train, y_train)
    y_pred_test = clf.predict(X_test) #train
    test_acc = accuracy_score(y_pred_test, y_test)

    if ((train_acc > relative_best_train_score) and (test_acc > relative_best_test_score)):
        relative_best_train_score = train_acc
        relative_best_test_score = test_acc
        relative_best_ratio = k
        

print("best ratio of testing data:", relative_best_ratio, "Testing score:", relative_best_test_score)